#include <iostream>
#include <stdlib.h>
#include <ctime>
#include <string>
#include <fstream>
using namespace std;

string Gname;

int Random(int max, int min);
void Ginstructions();
int Gloop(int ans);
void Gsavescore(int d, int score);
void Gviewscore(int d);

void GTNGame()
{
    int opt,dif,score;
    do{
        Ginstructions();
        cout << "1. Play\n2. View score\n3. Go back\n\n";
        cout << "Option: ";
        cin >> opt;

        switch(opt)
        {
            case 1:
                do{
                    cout << "1. Easy (1 - 100)\n2. Medium (101 - 1000)\n3. Hard (1001 - 10000)\n4. Go back\n";
                    cout << "\nDifficulty: ";
                    cin >> dif;

                    switch(dif)
                    {
                        case 1:
                            cout << "Enter your name: ";
                            cin >> Gname;
                            system("cls");
                            score = Gloop(Random(100, 1));
                            Gsavescore(1, score);
                            break;
                        case 2:
                            cout << "Enter your name: ";
                            cin >> Gname;
                            system("cls");
                            score = Gloop(Random(1000, 101));
                            Gsavescore(2, score);
                            break;
                        case 3:
                            cout << "Enter your name: ";
                            cin >> Gname;
                            system("cls");
                            score = Gloop(Random(10000, 1001));
                            Gsavescore(3, score);
                            break;
                        case 4:
                            cout << "Going back\n";
                        default:
                            cout << "Enter the Correct difficulty option\n\n";
                    }

                }while(dif != 4);
                break;
            case 2:
                do{
                    cout << "1. Easy (1 - 100)\n2. Medium (101 - 1000)\n3. Hard (1001 - 10000)\n4. Go back\n";
                    cout << "\nDifficulty: ";
                    cin >> dif;

                    switch(dif)
                    {
                        case 1:
                            Gviewscore(1);
                            break;
                        case 2:
                            Gviewscore(2);
                            break;
                        case 3:
                            Gviewscore(3);
                            break;
                        case 4:
                            cout << "Going back\n";
                        default:
                            cout << "Enter the Correct difficulty option\n\n";
                    }

                }while(dif != 4);
                break;
            case 3:
                cout << "Going Back\n";
                break;
            default:
                cout << "Enter the correct option\n";
        }
    }while(opt != 3);
}

int Random(int max, int min)
{
	int ans;
	srand(time(0));
	ans = (rand() % max)+min;

    return ans;
}

void Ginstructions()
{
    cout << "Welcome to Guess the number!\nYou have to guess a random number generated by the computer\n";
    cout << "Guess the number in less number of tries.\n";
    cout << "You can select the range in three difficulties.\n\n";
}

int Gloop(int ans)
{
	int guess, score = 0;
	
	do{
		cout<<"Enter your guess: ";
		cin>>guess;
		score++;
		if(guess>ans)
		{
			cout<<"Too high"<<endl;
		}
		else if(guess<ans)
		{
			cout<<"Too low"<<endl;
		}
	}while(guess != ans);
	
	cout <<"Congratulations!!!, correct answer is " << guess;
    cout <<"\n\nYour score: " << score << endl;

    return score;
}

void Gsavescore(int d, int score)
{
    fstream file;
    if(d == 1)
    {
        file.open("GuessScore100.txt", ios::app);
    }
    else if(d == 2)
    {
        file.open("GuessScore1000.txt", ios::app);
    }
    else if(d == 3)
    {
        file.open("GuessScore10000.txt", ios::app);
    }

    if(file.is_open())
    {
        file << Gname << "\t\t" << score << "\n";
        file.close();
    }
}

void Gviewscore(int d)
{
    string str;
    fstream file;
    if(d == 1)
    {
        file.open("GuessScore100.txt", ios::in);
    }
    else if(d == 2)
    {
        file.open("GuessScore1000.txt", ios::in);
    }
    else if(d == 3)
    {
        file.open("GuessScore10000.txt", ios::in);
    }
    
    if(file.is_open())
    {
        while(getline(file,str))
        {
            cout << str << endl;
        }
        file.close();
    }
    cout << "-----------END-----------\n";
}